[package]
name = "rivaldsend-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rivaldsend-proto = { path = "../rivaldsend-proto" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
blake3 = { workspace = true }
uuid = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
hkdf = "0.12"
sha2 = "0.10"
subtle = "2.5"
keyring = "2.3"
mdns-sd = "0.11"
if-addrs = "0.13"

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3.10"
